name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  release-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build release APK
      run: ./gradlew assembleRelease
      
    - name: Sign APK
      id: sign_apk
      run: |
        # For now, we'll use the unsigned APK
        # In the future, you can add signing configuration here
        cp app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/ProgressPal-${{ github.event.inputs.version || github.event.release.tag_name }}.apk
        echo "apk_path=app/build/outputs/apk/release/ProgressPal-${{ github.event.inputs.version || github.event.release.tag_name }}.apk" >> $GITHUB_OUTPUT
        
    - name: Upload Release APK to GitHub Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.sign_apk.outputs.apk_path }}
        asset_name: ProgressPal-${{ github.event.release.tag_name }}.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Upload APK as artifact (manual dispatch)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: ProgressPal-release-${{ github.event.inputs.version }}
        path: ${{ steps.sign_apk.outputs.apk_path }}
        retention-days: 90